---
######!!!!! DO NOT SAVE THIS AS TEMPLATE.Rmd ... GIVE IT A NEW NAME !!!!!######
title: "Module: Example Homework Format"   ## Don't change next thirteen lines
author: "Derek H. Ogle"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: pygments
    code_folding: hide
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=TRUE,fig.width=5,fig.height=5,comment="#R>")
```


<!---- You can edit anything below here ---->

# Packages and Data
```{r packages, eval=-1, message=FALSE, warning=FALSE}
setwd("https://derekogle.com/NCGraphing/") ## Set for your computer, delete eval=-1
library(tidyverse)
```

```{r data, echo=-1}
## Initially load data here
avoc <- read.csv("Avocados.csv",stringsAsFactors=FALSE,quote="") %>%
  filter(region=="GreatLakes") %>%
  mutate(type=factor(type),
         year=factor(year))
```


# Average Price vs Total Bags Sold

```{r fig.width=6.5}
avoc1 <- ggplot(data=avoc,mapping=aes(x=AveragePrice,y=Total.Bags,
                                      color=year,shape=type)) +
  geom_point(size=3,alpha=0.75) +
  scale_x_continuous(name="Average Price of An Avocados ($)") +
  scale_y_continuous(name="Total Number of Bags Sold") +
  scale_color_manual(values=c("#000000","#E69F00","#009E73","#CC79A7")) +
  theme_bw()
avoc1
```

