---
layout: page
title: Exercise - Pivoting
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage (CTRL-S and CTRL-ALT-R)
source(file.path(here::here(),"rhelpers/rhelpers.R"))
fnm <- "CE_1"
dnm <- "modules/Pivoting"
modHTML(file.path(here::here(),dnm,fnm))
FSA::purl2(file.path(here::here(),dnm,paste0(fnm,".Rmd")),
           moreItems=c("opts_chunk","kable","row_spec"))
```
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,results="hide",message=FALSE)
library(tidyverse)
library(kableExtra)
```

----

## Pivot Identification I

```{r ABC, echo=FALSE}
A <- data.frame(student=1:5,
                name=c("Jamila","Frank","Rose","Courtney","Lavelle"),
                year=c("JR","SR","SR","SO","JR"),
                pretest=c(84,76,65,85,81),
                posttest=c(91,88,77,86,91))
B <- data.frame(dog=1:4,
                breed=c("Sheltie","Black Lab","German Shepherd","Sheltie"),
                height=c(17,18,29,14),
                weight=c(27,45,58,19))
C <- data.frame(county=rep(c("Ramsey","Hennepin","Dakota"),times=2),
                est=rep(c(1849,1852,1849)),
                type=rep(c("size","population"),each=3),
                info=c(155.78,508640,556.62,1152425,569.58,398.552))
```
```{r results='markup'}
knitr::kable(A,align="c",caption="Data frame A") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed"),position="float_left") %>%
  row_spec(0,bold=TRUE)
knitr::kable(B,align="c",caption="Data frame B") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed"),position="float_left") %>%
  row_spec(0,bold=TRUE)
knitr::kable(C,align="c",caption="Data frame C") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed"),position="right") %>%
  row_spec(0,bold=TRUE)
```


