---
layout: page
title: Exercise - Relational Data
author: Derek H. Ogle
css: "/css/modules.css"
output:
  html_document:
    self_contained: false
    lib_dir: zlibs
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage (CTRL-S and CTRL-ALT-R)
source(file.path(here::here(),"rhelpers/rhelpers.R"))
fnm <- "CE_1"
dnm <- "modules/Relational-Data"
modHTML(file.path(here::here(),dnm,fnm))
FSA::purl2(file.path(here::here(),dnm,paste0(fnm,".Rmd")),
           moreItems=c("opts_chunk"))
```
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,results="hide",message=FALSE)
library(tidyverse)
library(kableExtra)
```

----

## Join Identification I
Suppose that you have two simple data frames `A` and `B`.

```{r AB, echo=FALSE}
A <- data.frame(uniq=c("A13","A15","A15","A16","A16"),
                meas1=c(34,87,65,33,12),
                meas2=c("sun","sun","moon","moon","sun"))
B <- data.frame(uniq=c("A14","A15","A16","A17"),
                meas3=c("am","pm","am","pm"))
```
```{r results='markup'}
knitr::kable(A,align="c",caption="Data frame A") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed"),position="float_left") %>%
  row_spec(0,bold=TRUE)
knitr::kable(B,align="c",caption="Data frame B") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed"),position="right") %>%
  row_spec(0,bold=TRUE)
```

<!-- for clearing the floats from above -->
<div style="clear:both;"></div>

Write what R code would be used to create each of the data frames shown below.

1. Data frame Z
```{r Z}
Z <- inner_join(A,B,by="uniq")
```
```{r results='markup'}
knitr::kable(Z,align="c") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed","striped")) %>%
  row_spec(0,bold=TRUE)
```

2. Data frame Y
```{r Y}
Y <- semi_join(A,B,by="uniq")
```
```{r results='markup'}
knitr::kable(Z,align="c") %>%
  kable_classic(full_width=FALSE,html_font="Cambria") %>%
  kable_styling(bootstrap_options=c("hover","condensed","striped")) %>%
  row_spec(0,bold=TRUE)
```

